name: godot-ci

on:
  push:
    branches: [ main ]

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: cyberiaesc
  PROJECT_PATH: cyberiaesc

jobs:
  export-web:
    name: Web Build and Publish
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "Web" ./build/web/index.html

      - name: Deploy to Itch
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: cyberiaesc
          ITCH_USER: portzero
          PACKAGE: build/web

      - name: Notify Discord Channel
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'A game update is available at https://portzero.itch.io/cyberiaesc !'